name = "Danesis"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://danbahrami.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Dan Bahrami"
  homepage = "http://danbahrami.com"